### ISSUE TITLE
page/search.scss 编译报错

### ISSUE THREAD

**Issue by BruceYuj** [Mrminfive/hexo-theme-skapp#8] opened 2017-10-10 06:13 UTC
@keyframes loader {
        from { transform: translate(-50%, -50%) rotate(0) },
        to { transform: translate(-50%, -50%) rotate(360deg) }
    }
改为
    @keyframes loader {
        from { transform: translate(-50%, -50%) rotate(0) }；
        to { transform: translate(-50%, -50%) rotate(360deg) }
    }

**Comment by Mrminfive** [comment] 2017-10-11 14:00
Duplicate of #6

**Closed** 2017-10-11 14:00 UTC
